name = "discord-oidc"
main = "worker.js"
compatibility_date = "2026-07-30"
keep_vars = true

[vars]
DISCORD_CLIENT_ID = "000000000000000000"
CLOUDFLARE_ACCESS_REDIRECT_URL = "https://your-team.cloudflareaccess.com/cdn-cgi/access/callback"
DISCORD_GUILD_IDS = "[]"

[[kv_namespaces]]
binding = "KV"
